# Generated by Django 5.0.1 on 2024-02-29 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myyapp', '0005_alter_appointment_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.DateTimeField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myyapp.appointment')),
            ],
        ),
    ]
