# Generated by Django 5.0.1 on 2024-02-29 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myyapp', '0006_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='appointment_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='appointment_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
